spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=PRC
    username: root
    password: root
    # password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/**/*Mapper.xml
